### ISSUE TITLE
RuntimeException: Unable to create service , BadTokenException: Unable to add window -- permission denied for window type 2002

### ISSUE THREAD

**Issue by ahmedwahba** [ahmedwahba/cordova-plugin-drawoverapps#11]
Ive tried all suggestions over the forums.
made changes accordingly.

Project compiles ok now, but I get error when executing function : overApps.startOverApp

I grabbed the adb log for this:
```
[ 10-17 14:01:39.176 18486:18486 E/AndroidRuntime ]
FATAL EXCEPTION: main
Process: in.iocare.itm, PID: 18486
java.lang.RuntimeException: Unable to create service org.apache.cordova.overApps.Services.OverAppsService: android.view.WindowManager$BadTokenException: Unable to add window android.view.ViewRootImpl$W@117abfa -- permission denied for window type 2002
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:3965)
        at android.app.ActivityThread.access$1500(ActivityThread.java:219)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1875)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
Caused by: android.view.WindowManager$BadTokenException: Unable to add window android.view.ViewRootImpl$W@117abfa -- permission denied for window type 2002
        at android.view.ViewRootImpl.setView(ViewRootImpl.java:931)
        at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:387)
        at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:95)
        at org.apache.cordova.overApps.Services.OverAppsService.onCreate(OverAppsService.java:127)
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:3953)
        ... 8 more

```

I have proper permission granted for app.

_Originally posted by @bkrajendra in https://github.com/ahmedwahba/cordova-plugin-drawoverapps/issues/1#issuecomment-543069644_

**Comment by bkrajendra** [comment]
Oh thank you @ahmedwahba .. I was going to this. And you done it for me.
By the way I have resolve this issue also.
Your OverAppsService.java code need to change a little bit to make it working on new sdk as LayoutParams.TYPE_PHONE is deprecated.

I'll post more about this with details.

**Comment by bkrajendra** [comment]
Ive resolved this issue temperorily by replacing line number 127, 135, 246 and 242
in file OverAppsService.java:
```WindowManager.LayoutParams.TYPE_PHONE```
by
```WindowManager.LayoutParams.TYPE_APPLICATION_OVERLAY```
A proper solution can be as follows.

I suggest @ahmedwahba to look into this issue and do the necessary changes in OverAppsService.java.
This is working for me as Im on Android Q and compiling with min-sdk=19 and compile sdk 28+

But more proper way we need to check android build version before using.
I suggest its better to keep it as:

```
if (android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.O) {
	params_key_dispature = new WindowManager.LayoutParams(
			 WindowManager.LayoutParams.WRAP_CONTENT,
			 WindowManager.LayoutParams.WRAP_CONTENT,
			 WindowManager.LayoutParams.TYPE_APPLICATION_OVERLAY,
			 WindowManager.LayoutParams.FLAG_NOT_FOCUSABLE,
			 PixelFormat.TRANSLUCENT);

	params_key_dispature.type = WindowManager.LayoutParams.TYPE_APPLICATION_OVERLAY;

} else {
    params_key_dispature = new WindowManager.LayoutParams(
                WindowManager.LayoutParams.WRAP_CONTENT,
                WindowManager.LayoutParams.WRAP_CONTENT,
                WindowManager.LayoutParams.TYPE_PHONE,
                WindowManager.LayoutParams.FLAG_NOT_FOCUSABLE,
                PixelFormat.TRANSLUCENT);

	params_key_dispature.type = WindowManager.LayoutParams.TYPE_PHONE;
}
```

Ive not tested this but should work.

**Comment by ahmedwahba** [comment]
@bkrajendra thanks for great effort , changes will be added next update

**Comment by acedigibits** [comment]
kindly release this update plz
