### ISSUE TITLE
error: "package R does not exist" on several lines of OverAppsService.java

### ISSUE THREAD

**Issue by druidtton** [ahmedwahba/cordova-plugin-drawoverapps#4]
So after installing your plugin and its dependencies I attempted to run my app to do a test, I keep getting the error below which points to the OverAppsService.java file starting on line 77 telling me that the "package R does not exist". I tried importing R by adding the line 
`import org.apache.cordova.overApps.DrawOverApps.R;` however this did not solve the issue. I've already tried all 3 forks of your plugin and all of them present the same problem. 

I am using cordova 7.0.1, I know the last time this plugin was said to be successfully tested by yourself it was on cordova 6.5.0, but I have not yet downgraded to that version to test it. Do you think I should, or can you see any quick fix that might get this running with the latest versions of cordova?

I am no good at Java, which is the main reason I'm using cordova in the first place, so I would appreciate any help or insight.

```
Error: cmd: Command failed with exit code 1 Error output:
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
C:\Users\admin\Desktop\neckSaver\CORDOVA\textNeckTest\platforms\android\src\org\apache\cordova\overApps\Services\OverAppsService.java:77: error: package R does not exist
         overAppsHead = inflater.inflate(R.layout.service_over_apps_head, null, false);
                                          ^
C:\Users\admin\Desktop\neckSaver\CORDOVA\textNeckTest\platforms\android\src\org\apache\cordova\overApps\Services\OverAppsService.java:78: error: package R does not exist
         overAppsView = inflater.inflate(R.layout.service_over_apps_view, null, false);
                                          ^
C:\Users\admin\Desktop\neckSaver\CORDOVA\textNeckTest\platforms\android\src\org\apache\cordova\overApps\Services\OverAppsService.java:79: error: package R does not exist
         webView = (WebView) overAppsView.findViewById(R.id.webView);
                                                        ^
C:\Users\admin\Desktop\neckSaver\CORDOVA\textNeckTest\platforms\android\src\org\apache\cordova\overApps\Services\OverAppsService.java:80: error: package R does not exist
         imageHead = (ImageView) overAppsHead.findViewById(R.id.imageHead);
                                                            ^
C:\Users\admin\Desktop\neckSaver\CORDOVA\textNeckTest\platforms\android\src\org\apache\cordova\overApps\Services\OverAppsService.java:81: error: package R does not exist
         imgClose = (ImageView) overAppsView.findViewById(R.id.imgClose);
                                                           ^
C:\Users\admin\Desktop\neckSaver\CORDOVA\textNeckTest\platforms\android\src\org\apache\cordova\overApps\Services\OverAppsService.java:209: error: package R does not exist
             keyDispatureView = inflater.inflate(R.layout.key_dispature, null, false);
                                                  ^
C:\Users\admin\Desktop\neckSaver\CORDOVA\textNeckTest\platforms\android\src\org\apache\cordova\overApps\Services\OverAppsService.java:211: error: package R does not exist
         rlKeyDispature = (KeyDispatchLayout) keyDispatureView.findViewById(R.id.tab_left);
                                                                             ^
Note: C:\Users\admin\Desktop\neckSaver\CORDOVA\textNeckTest\platforms\android\src\org\apache\cordova\overApps\Services\OverAppsService.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
7 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
```

**Comment by ahmedwahba** [comment]
please check  **cordova-plugin-device** in your plugins if not installed then install it & reinstall the plugin

**Comment by dukelec** [comment]
Still not work, this is log:
```
duke@duke-pc /mnt/TF/projects/cordova/nophone $ cordova plugin rm cordova-plugin-device
Uninstalling cordova-plugin-device from android
Android Studio project detected
Removing "cordova-plugin-device"
Removing plugin cordova-plugin-device from config.xml file...
Removing cordova-plugin-device from package.json
duke@duke-pc /mnt/TF/projects/cordova/nophone $ 
duke@duke-pc /mnt/TF/projects/cordova/nophone $ 
duke@duke-pc /mnt/TF/projects/cordova/nophone $ cordova plugin install cordova-plugin-device
cordova-plugin-autostart 2.3.0 "Autostart"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-console 1.1.0 "Console"
cordova-plugin-drawoverapps 1.0.5 "Cordova Draw Over Apps"
cordova-plugin-whitelist 1.3.3 "Whitelist"
duke@duke-pc /mnt/TF/projects/cordova/nophone $ cordova run android
Android Studio project detected
ANDROID_HOME=/mnt/TT/software/android-sdk
JAVA_HOME=/mnt/TT/software/android-sdk/jdk1.8.0_172
studio
Subproject Path: CordovaLib
Subproject Path: app
publishNonDefault is deprecated and has no effect anymore. All variants are now published.
Configuration 'compile' in project ':app' is deprecated. Use 'implementation' instead.
The Task.leftShift(Closure) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use Task.doLast(Action) instead.
	at build_9vch3q9hl8eps5hyyd9veilqh.run(/mnt/TF/projects/cordova/nophone/platforms/android/app/build.gradle:144)
:CordovaLib:preBuild UP-TO-DATE
:CordovaLib:preDebugBuild UP-TO-DATE
:CordovaLib:compileDebugAidl UP-TO-DATE
:CordovaLib:compileDebugRenderscript UP-TO-DATE
:CordovaLib:checkDebugManifest UP-TO-DATE
:CordovaLib:generateDebugBuildConfig UP-TO-DATE
:CordovaLib:prepareLintJar UP-TO-DATE
:CordovaLib:generateDebugResValues UP-TO-DATE
:CordovaLib:generateDebugResources UP-TO-DATE
:CordovaLib:packageDebugResources UP-TO-DATE
:CordovaLib:platformAttrExtractor UP-TO-DATE
:CordovaLib:processDebugManifest UP-TO-DATE
:CordovaLib:processDebugResources UP-TO-DATE
:CordovaLib:generateDebugSources UP-TO-DATE
:CordovaLib:javaPreCompileDebug UP-TO-DATE
:CordovaLib:compileDebugJavaWithJavac UP-TO-DATE
:CordovaLib:processDebugJavaRes NO-SOURCE
:CordovaLib:transformClassesAndResourcesWithPrepareIntermediateJarsForDebug UP-TO-DATE
:app:preBuild UP-TO-DATE
:app:preDebugBuild UP-TO-DATE
:app:compileDebugAidl UP-TO-DATE
:CordovaLib:packageDebugRenderscript NO-SOURCE
:app:compileDebugRenderscript UP-TO-DATE
:app:checkDebugManifest UP-TO-DATE
:app:generateDebugBuildConfig UP-TO-DATE
:app:prepareLintJar UP-TO-DATE
:app:generateDebugResValues UP-TO-DATE
:app:generateDebugResources UP-TO-DATE
:app:mergeDebugResources
:app:createDebugCompatibleScreenManifests UP-TO-DATE
:app:processDebugManifest UP-TO-DATE
:app:splitsDiscoveryTaskDebug UP-TO-DATE
:app:processDebugResources
:app:generateDebugSources
:app:javaPreCompileDebug UP-TO-DATE
:app:compileDebugJavaWithJavac/mnt/TF/projects/cordova/nophone/platforms/android/app/src/main/java/org/apache/cordova/overApps/Services/OverAppsService.java:77: error: package R does not exist
         overAppsHead = inflater.inflate(R.layout.service_over_apps_head, null, false);
                                          ^
/mnt/TF/projects/cordova/nophone/platforms/android/app/src/main/java/org/apache/cordova/overApps/Services/OverAppsService.java:78: error: package R does not exist
         overAppsView = inflater.inflate(R.layout.service_over_apps_view, null, false);
                                          ^
/mnt/TF/projects/cordova/nophone/platforms/android/app/src/main/java/org/apache/cordova/overApps/Services/OverAppsService.java:79: error: package R does not exist
         webView = (WebView) overAppsView.findViewById(R.id.webView);
                                                        ^
/mnt/TF/projects/cordova/nophone/platforms/android/app/src/main/java/org/apache/cordova/overApps/Services/OverAppsService.java:80: error: package R does not exist
         imageHead = (ImageView) overAppsHead.findViewById(R.id.imageHead);
                                                            ^
/mnt/TF/projects/cordova/nophone/platforms/android/app/src/main/java/org/apache/cordova/overApps/Services/OverAppsService.java:81: error: package R does not exist
         imgClose = (ImageView) overAppsView.findViewById(R.id.imgClose);
                                                           ^
/mnt/TF/projects/cordova/nophone/platforms/android/app/src/main/java/org/apache/cordova/overApps/Services/OverAppsService.java:209: error: package R does not exist
             keyDispatureView = inflater.inflate(R.layout.key_dispature, null, false);
                                                  ^
/mnt/TF/projects/cordova/nophone/platforms/android/app/src/main/java/org/apache/cordova/overApps/Services/OverAppsService.java:211: error: package R does not exist
         rlKeyDispature = (KeyDispatchLayout) keyDispatureView.findViewById(R.id.tab_left);
                                                                             ^
Note: /mnt/TF/projects/cordova/nophone/platforms/android/app/src/main/java/org/apache/cordova/overApps/Services/OverAppsService.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
7 errors
 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
27 actionable tasks: 3 executed, 24 up-to-date
(node:31542) UnhandledPromiseRejectionWarning: Error: /mnt/TF/projects/cordova/nophone/platforms/android/gradlew: Command failed with exit code 1 Error output:
/mnt/TF/projects/cordova/nophone/platforms/android/app/src/main/java/org/apache/cordova/overApps/Services/OverAppsService.java:77: error: package R does not exist
         overAppsHead = inflater.inflate(R.layout.service_over_apps_head, null, false);
                                          ^
/mnt/TF/projects/cordova/nophone/platforms/android/app/src/main/java/org/apache/cordova/overApps/Services/OverAppsService.java:78: error: package R does not exist
         overAppsView = inflater.inflate(R.layout.service_over_apps_view, null, false);
                                          ^
/mnt/TF/projects/cordova/nophone/platforms/android/app/src/main/java/org/apache/cordova/overApps/Services/OverAppsService.java:79: error: package R does not exist
         webView = (WebView) overAppsView.findViewById(R.id.webView);
                                                        ^
/mnt/TF/projects/cordova/nophone/platforms/android/app/src/main/java/org/apache/cordova/overApps/Services/OverAppsService.java:80: error: package R does not exist
         imageHead = (ImageView) overAppsHead.findViewById(R.id.imageHead);
                                                            ^
/mnt/TF/projects/cordova/nophone/platforms/android/app/src/main/java/org/apache/cordova/overApps/Services/OverAppsService.java:81: error: package R does not exist
         imgClose = (ImageView) overAppsView.findViewById(R.id.imgClose);
                                                           ^
/mnt/TF/projects/cordova/nophone/platforms/android/app/src/main/java/org/apache/cordova/overApps/Services/OverAppsService.java:209: error: package R does not exist
             keyDispatureView = inflater.inflate(R.layout.key_dispature, null, false);
                                                  ^
/mnt/TF/projects/cordova/nophone/platforms/android/app/src/main/java/org/apache/cordova/overApps/Services/OverAppsService.java:211: error: package R does not exist
         rlKeyDispature = (KeyDispatchLayout) keyDispatureView.findViewById(R.id.tab_left);
                                                                             ^
Note: /mnt/TF/projects/cordova/nophone/platforms/android/app/src/main/java/org/apache/cordova/overApps/Services/OverAppsService.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
7 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
    at ChildProcess.whenDone (/mnt/TF/projects/cordova/nophone/platforms/android/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
(node:31542) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:31542) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
duke@duke-pc /mnt/TF/projects/cordova/nophone $
```

The log when I install your plugin:
```
duke@duke-pc /mnt/TF/projects/cordova/nophone $ cordova plugin add https://github.com/ahmedwahba/cordova-plugin-drawoverapps
Installing "cordova-plugin-drawoverapps" for android
Installing "cordova-plugin-compat" for android
Plugin doesn't support this project's cordova-android version. cordova-android: 7.0.0, failed version requirement: 
      <6.3.0
Skipping 'cordova-plugin-compat' for android
Android Studio project detected
Subproject Path: CordovaLib
Subproject Path: app
No android platform found! :(
Adding cordova-plugin-drawoverapps to package.json
Saved plugin info for "cordova-plugin-drawoverapps" to config.xml
duke@duke-pc /mnt/TF/projects/cordova/nophone $ 
```

**Comment by ahmedwahba** [comment]
plugin has a hook to add your package R classes to your platform file , so just remove the platform using `cordova platform rm android ` then after making sure you have device plugin you can install this plugin

**Comment by dukelec** [comment]
Thanks for your reply, but still not work:
```
duke@duke-pc /mnt/TF/projects/cordova/nophone $ cordova platform rm android
Removing platform android from config.xml file...
Removing android from cordova.platforms array in package.json
duke@duke-pc /mnt/TF/projects/cordova/nophone $ cordova plugin uninstall cordova-plugin-drawoverapps
cordova-plugin-autostart 2.3.0 "Autostart"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-console 1.1.0 "Console"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-drawoverapps 1.0.5 "Cordova Draw Over Apps"
cordova-plugin-whitelist 1.3.3 "Whitelist"
duke@duke-pc /mnt/TF/projects/cordova/nophone $ 
duke@duke-pc /mnt/TF/projects/cordova/nophone $ 
duke@duke-pc /mnt/TF/projects/cordova/nophone $ 
duke@duke-pc /mnt/TF/projects/cordova/nophone $ cordova plugin add https://github.com/ahmedwahba/cordova-plugin-drawoverapps
Adding cordova-plugin-drawoverapps to package.json
Saved plugin info for "cordova-plugin-drawoverapps" to config.xml
duke@duke-pc /mnt/TF/projects/cordova/nophone $ cordova platform add android
Using cordova-fetch for cordova-android@~7.0.0
Adding android project...
Creating Cordova project for the Android platform:
	Path: platforms/android
	Package: com.dukelec.nophone
	Name: NoPhone
	Activity: MainActivity
	Android target: android-26
Subproject Path: CordovaLib
Subproject Path: app
Android project created with cordova-android@7.0.0
Android Studio project detected
Android Studio project detected
Installing "cordova-plugin-autostart" for android
Installing "cordova-plugin-compat" for android
Plugin doesn't support this project's cordova-android version. cordova-android: 7.0.0, failed version requirement: 
      <6.3.0
Skipping 'cordova-plugin-compat' for android
Installing "cordova-plugin-console" for android
Installing "cordova-plugin-device" for android
Installing "cordova-plugin-drawoverapps" for android
Plugin dependency "cordova-plugin-compat@1.2.0" already fetched, using that version.
Installing "cordova-plugin-compat" for android
Plugin doesn't support this project's cordova-android version. cordova-android: 7.0.0, failed version requirement: 
      <6.3.0
Skipping 'cordova-plugin-compat' for android
Subproject Path: CordovaLib
Subproject Path: app
No android platform found! :(
Installing "cordova-plugin-whitelist" for android

               This plugin is only applicable for versions of cordova-android greater than 4.0. If you have a previous platform version, you do *not* need this plugin since the whitelist will be built in.
          
--save flag or autosave detected
Saving android@~7.0.0 into config.xml file ...
duke@duke-pc /mnt/TF/projects/cordova/nophone $ cordova run android
Android Studio project detected
ANDROID_HOME=/mnt/TT/software/android-sdk
JAVA_HOME=/mnt/TT/software/android-sdk/jdk1.8.0_172
studio
Starting a Gradle Daemon (subsequent builds will be faster)
:wrapper

BUILD SUCCESSFUL

Total time: 4.128 secs
Subproject Path: CordovaLib
Subproject Path: app
Starting a Gradle Daemon (subsequent builds will be faster)
publishNonDefault is deprecated and has no effect anymore. All variants are now published.
Configuration 'compile' in project ':app' is deprecated. Use 'implementation' instead.
The Task.leftShift(Closure) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use Task.doLast(Action) instead.
	at build_9vch3q9hl8eps5hyyd9veilqh.run(/mnt/TF/projects/cordova/nophone/platforms/android/app/build.gradle:144)
:CordovaLib:preBuild UP-TO-DATE
:CordovaLib:preDebugBuild UP-TO-DATE
:CordovaLib:compileDebugAidl
:CordovaLib:compileDebugRenderscript
:CordovaLib:checkDebugManifest
:CordovaLib:generateDebugBuildConfig
:CordovaLib:prepareLintJar
:CordovaLib:generateDebugResValues
:CordovaLib:generateDebugResources
:CordovaLib:packageDebugResources
:CordovaLib:platformAttrExtractor
:CordovaLib:processDebugManifest
:CordovaLib:javaPreCompileDebug
:CordovaLib:processDebugResources
:CordovaLib:generateDebugSources
:CordovaLib:compileDebugJavaWithJavacNote: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

:CordovaLib:processDebugJavaRes NO-SOURCE
:CordovaLib:transformClassesAndResourcesWithPrepareIntermediateJarsForDebug
:app:preBuild UP-TO-DATE
:app:preDebugBuild
:app:compileDebugAidl
:CordovaLib:packageDebugRenderscript NO-SOURCE
:app:compileDebugRenderscript
:app:checkDebugManifest
:app:generateDebugBuildConfig
:app:prepareLintJar
:app:generateDebugResValues
:app:generateDebugResources
:app:mergeDebugResources
:app:createDebugCompatibleScreenManifests
:app:processDebugManifest
:app:splitsDiscoveryTaskDebug
:app:processDebugResources
:app:generateDebugSources
:app:javaPreCompileDebug
:app:compileDebugJavaWithJavac/mnt/TF/projects/cordova/nophone/platforms/android/app/src/main/java/org/apache/cordova/overApps/Services/OverAppsService.java:77: error: package R does not exist
         overAppsHead = inflater.inflate(R.layout.service_over_apps_head, null, false);
                                          ^
/mnt/TF/projects/cordova/nophone/platforms/android/app/src/main/java/org/apache/cordova/overApps/Services/OverAppsService.java:78: error: package R does not exist
         overAppsView = inflater.inflate(R.layout.service_over_apps_view, null, false);
                                          ^
/mnt/TF/projects/cordova/nophone/platforms/android/app/src/main/java/org/apache/cordova/overApps/Services/OverAppsService.java:79: error: package R does not exist
         webView = (WebView) overAppsView.findViewById(R.id.webView);
                                                        ^
/mnt/TF/projects/cordova/nophone/platforms/android/app/src/main/java/org/apache/cordova/overApps/Services/OverAppsService.java:80: error: package R does not exist
         imageHead = (ImageView) overAppsHead.findViewById(R.id.imageHead);
                                                            ^
/mnt/TF/projects/cordova/nophone/platforms/android/app/src/main/java/org/apache/cordova/overApps/Services/OverAppsService.java:81: error: package R does not exist
         imgClose = (ImageView) overAppsView.findViewById(R.id.imgClose);
                                                           ^
/mnt/TF/projects/cordova/nophone/platforms/android/app/src/main/java/org/apache/cordova/overApps/Services/OverAppsService.java:209: error: package R does not exist
             keyDispatureView = inflater.inflate(R.layout.key_dispature, null, false);
                                                  ^
/mnt/TF/projects/cordova/nophone/platforms/android/app/src/main/java/org/apache/cordova/overApps/Services/OverAppsService.java:211: error: package R does not exist
         rlKeyDispature = (KeyDispatchLayout) keyDispatureView.findViewById(R.id.tab_left);
                                                                             ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
7 errors
 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 25s
27 actionable tasks: 27 executed
(node:28945) UnhandledPromiseRejectionWarning: Error: /mnt/TF/projects/cordova/nophone/platforms/android/gradlew: Command failed with exit code 1 Error output:
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
/mnt/TF/projects/cordova/nophone/platforms/android/app/src/main/java/org/apache/cordova/overApps/Services/OverAppsService.java:77: error: package R does not exist
         overAppsHead = inflater.inflate(R.layout.service_over_apps_head, null, false);
                                          ^
/mnt/TF/projects/cordova/nophone/platforms/android/app/src/main/java/org/apache/cordova/overApps/Services/OverAppsService.java:78: error: package R does not exist
         overAppsView = inflater.inflate(R.layout.service_over_apps_view, null, false);
                                          ^
/mnt/TF/projects/cordova/nophone/platforms/android/app/src/main/java/org/apache/cordova/overApps/Services/OverAppsService.java:79: error: package R does not exist
         webView = (WebView) overAppsView.findViewById(R.id.webView);
                                                        ^
/mnt/TF/projects/cordova/nophone/platforms/android/app/src/main/java/org/apache/cordova/overApps/Services/OverAppsService.java:80: error: package R does not exist
         imageHead = (ImageView) overAppsHead.findViewById(R.id.imageHead);
                                                            ^
/mnt/TF/projects/cordova/nophone/platforms/android/app/src/main/java/org/apache/cordova/overApps/Services/OverAppsService.java:81: error: package R does not exist
         imgClose = (ImageView) overAppsView.findViewById(R.id.imgClose);
                                                           ^
/mnt/TF/projects/cordova/nophone/platforms/android/app/src/main/java/org/apache/cordova/overApps/Services/OverAppsService.java:209: error: package R does not exist
             keyDispatureView = inflater.inflate(R.layout.key_dispature, null, false);
                                                  ^
/mnt/TF/projects/cordova/nophone/platforms/android/app/src/main/java/org/apache/cordova/overApps/Services/OverAppsService.java:211: error: package R does not exist
         rlKeyDispature = (KeyDispatchLayout) keyDispatureView.findViewById(R.id.tab_left);
                                                                             ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
7 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 25s
    at ChildProcess.whenDone (/mnt/TF/projects/cordova/nophone/platforms/android/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
(node:28945) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:28945) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
duke@duke-pc /mnt/TF/projects/cordova/nophone $ find . -name "R.java"
./platforms/android/CordovaLib/build/generated/source/r/debug/org/apache/cordova/R.java
./platforms/android/app/build/generated/source/r/debug/org/apache/cordova/R.java
./platforms/android/app/build/generated/source/r/debug/com/dukelec/nophone/R.java
./platforms/android/app/build/generated/source/r/debug/com/makeramen/roundedimageview/R.java
duke@duke-pc /mnt/TF/projects/cordova/nophone $ 
duke@duke-pc /mnt/TF/projects/cordova/nophone $ ls plugins/ -l
total 32
-rw-r--r-- 1 duke duke  591 Jun 15 00:44 android.json
drwxr-xr-x 5 duke duke 4096 Jun 13 05:14 cordova-plugin-autostart
drwxr-xr-x 3 duke duke 4096 Jun 13 11:10 cordova-plugin-compat
drwxr-xr-x 6 duke duke 4096 Jun 13 04:15 cordova-plugin-console
drwxr-xr-x 7 duke duke 4096 Jun 13 11:08 cordova-plugin-device
drwxr-xr-x 5 duke duke 4096 Jun 15 00:40 cordova-plugin-drawoverapps
drwxr-xr-x 4 duke duke 4096 Jun 13 04:04 cordova-plugin-whitelist
-rw-r--r-- 1 duke duke 1091 Jun 15 00:40 fetch.json
duke@duke-pc /mnt/TF/projects/cordova/nophone $
```

**Comment by amrou25** [comment]
hi

i get error in phonegap build 
"package R does not exist"
aready i have installed device plugin but still i get same error

**Comment by bkrajendra** [comment]
removing and adding your android platform might fix your issue.

**Comment by budafly** [comment]
having the same problem with R

**Comment by dubrovskiyandrey** [comment]
Hi, 
This problem is still remains in phonegap build service.
And looks like the com.cordova.device has no R class inside

**Comment by rcpinheiro** [comment]
Same here. Installing com.cordova.device, uninstalling and installing Android platform is not enough to get rid of the problem. I think this plugin only works on very old cordova-android versions.

**Comment by ahmedwahba** [comment]
try last version 1.1.0

**Comment by DigitalDevelooper** [comment]
tried everything you mention above but the error is still the same

**Comment by ahmedwahba** [comment]
Please debug this hook file **hookToImportR.js**  and check if succeeds
